---
apiVersion: v1
kind: Pod
metadata:
  name: second-pod
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:latest-jdk11
      ports:
        - containerPort: 8080
          protocol: TCP
    - name: nginx
      image: nginx:1.23
      ports:
        - containerPort: 80
          protocol: TCP        