---
apiVersion: v1
kind: Pod
metadata: 
  name: restart-never
spec:
  restartPolicy: Never
  containers:
    - name: restart-never
      image: alpine:3.17
      command:
        - sleep
        -  "6"