---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  minReadySeconds: 30
  replicas: 4
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80
              protocol: TCP