---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-labels
  labels:
    app: nginx
    ver: "1.23"
spec:
  containers:
    - name: nginx1
      image: nginx:1.23
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-labels1
  labels:
    app: nginx
    ver: "1.23"
spec:
  containers:
    - name: nginx2
      image: nginx:1
      ports:
        - containerPort: 80
          protocol: TCP



