---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  labels:
    app: jenkins
    env: qa
    jdk: "11"
    ver: lts
spec:
  minReadySeconds: 3
  replicas: 4
  selector:
    matchLabels:
      app: jenkins
      env: qa
      jdk: "11"
      ver: lts
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
        env: qa
        jdk: "11"
        ver: lts
    spec:
      containers:
        - name: nginx
          image: nginx:1.23 
          ports:
            - containerPort: 8080
              protocol: TCP
      resources:
        requests:
          memory: "256Mi"
        limits:        
          memory: "500Mi"
        