---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
  annotations:
    kubernetes.io/role/internal-elb: "1"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: webport
      port: 38000
      targetPort: 80    