---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
spec:
  minReadySeconds: 4
  replicas: 4
  selector:
    matchLabels:
      app: jenkins
      ver: "1.0"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
        ver: "1.0"
    spec:
      containers:
        - name: jenkins
          image: jenkins:1.625.1
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            tcpSocket: 
              port: 8080                            
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: jenkins
    ver: "1.0"
  ports:
    - name: webport
      port: 38000
      targetPort: 8080                                
